name: build

on:
  push:
    branches:
      - "branch-*"
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
      date:
        required: true
        type: string
      sha:
        required: true
        type: string
      build_type:
        type: string
        default: nightly

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}

jobs:
  wheel-build-cudf:
    secrets: inherit
    uses: furkansahin/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.06
    with:
      build_type: ${{ inputs.build_type || 'branch' }}
      branch: ${{ inputs.branch }}
      sha: ${{ inputs.sha }}
      date: ${{ inputs.date }}
      script: ci/build_wheel_cudf.sh
  trigger-pandas-tests:
    needs: wheel-build-cudf
    runs-on: ubicloud-gpu-standard-1-latest
    steps:
      - name: Checkout code repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}
          persist-credentials: false
      - name: Trigger pandas-tests
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run pandas-tests.yaml \
            -f branch=${{ inputs.branch }} \
            -f sha=${{ inputs.sha }} \
            -f date=${{ inputs.date }}
