name: test

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
      date:
        required: true
        type: string
      sha:
        required: true
        type: string

jobs:
  unit-tests-cudf-pandas:
    secrets: inherit
    uses: furkansahin/shared-workflows/.github/workflows/wheels-test.yaml@branch-24.06
    with:
      build_type: nightly
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}
      script: ci/cudf_pandas_scripts/run_tests.sh
